services:
  postgres:
    image: postgres:16.2
    container_name: postgres
    ports:
      - "5432:5432"
    volumes:
      - ./_data:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: secret
      POSTGRES_DB: post_db
volumes:
  _data: